<a href="https://colab.research.google.com/github/kavyaanjali-nri/Age-Height-Weight-Speed/blob/main/Introduction%20to%20numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# Recape
arr = np.array([[1,2,3],[4,5,6,]])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
# Dot product - m x n || n x p
arr1 = np.random.randint(1,2,(1,2))

In [ ]:
arr1.shape

(1, 2)

In [ ]:
result = np.dot(arr1,arr)

In [ ]:
print(result)

[[5 7 9]]


In [ ]:
r1 = np.random.randint(10,20,(3,3))
print(r1)

[[18 11 10]
 [18 17 17]
 [13 16 15]]


In [ ]:
r2 = np.eye(3)
print(r2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# r1 .I
result2 = np.dot(r2,r1)


In [ ]:
print(result2)

[[18. 11. 10.]
 [18. 17. 17.]
 [13. 16. 15.]]


In [ ]:
# M - I = I .M = M

In [ ]:
#A .B ! = B . A

In [ ]:
#mathematical operation
# + - * /
t1 = np.random.randint(3,6,(3,3))
t2 = np.random.randint(3,6,(3,3))




In [ ]:
print(t1)
print(t2)



[[3 3 3]
 [5 5 5]
 [5 3 5]]
[[5 4 3]
 [3 5 5]
 [5 5 5]]


In [ ]:
t3 = t1 * t2

In [ ]:
print(t3)

[[15 12  9]
 [15 25 25]
 [25 15 25]]


In [ ]:
# Matrix multiplication
result = np.dot(arr1,arr)

In [ ]:
# Statistical operations
mean = t3.mean()
mode = t3.max()
median = np.median(t3)
std = np.std(t3)
var = np.var(t3)


In [ ]:
print(median)

15.0


In [ ]:
print(std)

6.130272988503877


In [ ]:
print(var)

37.58024691358025


In [ ]:
std * std

37.580246913580254

In [ ]:
# Trignometric functions
#Sin(x)
#cos(x)
#tan(x) - sin(x) / cos(x)
#cosec - 1 / sin(x)
#sec - 1 / cos(x)
#cot - 1 / tan(x)
#
angles = np.array([0,15,30,45,60,75,90])

#Sin (array)

result = np.sin(np.radians(angles))
result1 = np.cos(np.radians(angles))
result2 = np.tan(np.radians(angles))

In [ ]:
print(result)
print(result1)
print(result2)

[0.         0.25881905 0.5        0.70710678 0.8660254  0.96592583
 1.        ]
[1.00000000e+00 9.65925826e-01 8.66025404e-01 7.07106781e-01
 5.00000000e-01 2.58819045e-01 6.12323400e-17]
[0.00000000e+00 2.67949192e-01 5.77350269e-01 1.00000000e+00
 1.73205081e+00 3.73205081e+00 1.63312394e+16]


In [ ]:
arr = np.array([1,2,3,4,5,6])

#Reshape the array
reshapedarr = arr.reshape(3,2)

print(reshapedarr)

# convert / flatten any n din array
flattenedarr = arr.flatten()
print(flattenedarr)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [ ]:
# Stacking the data

arr1 = np.array([[1,2,3,4],[2,3,4,5]])
arr2 = np.array([10,20,30,40])

# Vertical Stacking
arr3 = np.vstack((arr1,arr2))
print(f"The shape of arr3 is {arr3.shape}")

#Horizontal Stacking
arr4 = np.hstack((arr1,arr2.reshape(2,2))) #Need to reshape to stack horizontally
print(f"The shape of arr4 is {arr4.shape}")
print(arr4)

The shape of arr3 is (3, 4)
The shape of arr4 is (2, 6)
[[ 1  2  3  4 10 20]
 [ 2  3  4  5 30 40]]


In [ ]:
#Filtering the data
arr = np.array([10,20,30,40,50,60,70,80])

farr = arr[arr > 40]

print(farr)

[50 60 70 80]
