<a href="https://colab.research.google.com/github/kavyaanjali-nri/Age-Height-Weight-Speed/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Numpy-Numeric python
# Most powerful packag-library

# Numpy - dimensions


# A- One dimensions Array
#[A,B] [] [ A B ] - TWO Dimensional Array-Row[]colmun


# three dimensional

#Array-Storing,manipulating,Similar data type

#faster then mathematical functions
#convinient compared to other package
#memory efficiency
#supportmulti dimensional array

#speed(Numpy operations)>speed(Lists operations)
#size(Numpy operations)<size(Lists operations)
#memory optimization(Numpy)>memory optimization(Lists operations)

In [ ]:
# Install numpy-pip3 install numpy // pip install numpy

In [ ]:
import numpy as np

In [ ]:
#creat a numpy array
# 1d array

arr1D = np.array([1,2,3,4,5,6,])
print(arr1D)

[1 2 3 4 5 6]


In [ ]:
# Creating 2D Array-matrix
arr2D = np.array([
    [1,2,3,4,5,6,]
])
print(arr2D)

[[1 2 3 4 5 6]]


In [ ]:
# Creating an identity matrix -I

identity = np.eye(4)
print(identity)

# Identity Matrix
#For all A Belong to R MXN
#AIJ-

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# Creating arrays with default values as '0'
allZeros = np.zeros((2,3)) # Removed extra indent
print(allZeros)

# Creating matrix with all values of elementes as '1'
allOnes = np.ones((2,3)) # Removed extra indent
print(allOnes)

# Creating matrix with all values of elementes 'constant values - n ~ Fill valuea'
allConstant = np.full((2,3),6) # Removed extra indent
print(allConstant)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[6 6 6]
 [6 6 6]]


In [ ]:
# creating random matrices

# between 0 and 1
rand1 = np.random.rand(2,3)
print(rand1)

#between a and b
rand2 = np. random.randint(10,20,(3,3))
print(rand2)

[[0.30288369 0.47564225 0.17062343]
 [0.40963341 0.38475823 0.26990959]]
[[18 10 17]
 [15 15 18]
 [19 15 11]]


In [ ]:
# Array properties

arr = np.array([[1,2,3],[2,3,4]])
print(arr)

# Shape or array
print(f'\nThe shape of the array is {arr.shape}')

# Size of array
print(f'The size of the array is {arr.size}')
# Datatype of array

print(f'The data type of the array is {arr.dtype}')

# Dimensions of array
print(f'The dimensions of the array is {arr.ndim}')

[[1 2 3]
 [2 3 4]]

The shape of the array is (2, 3)
The size of the array is 6
The data type of the array is int64
The dimensions of the array is 2


In [ ]:
# Indexing and Slicing

# Access the element in 1D Array

arr = np.array([1,2,3])
print(arr)
#print(arr[3]) # This line was causing the error.  Index 3 is out of bounds.
print(arr[2]) # Accessing the last element using index 2

#Slicing the element
print(arr[0:3])

# Access the element in 2D ARRAY
arr2 = np.array([[1,2,3],[2,3,4]])
print(arr2)
print(arr2[1,1])
print(arr2[0,:1])# first row with all columns
print

[1 2 3]
3
[1 2 3]
[[1 2 3]
 [2 3 4]]
3
[1]


<function print(*args, sep=' ', end='\n', file=None, flush=False)>

In [ ]:
# l1 = []
# [l1.append(_)for _ in range(30)]

l1 = np.arange(30,-30,-3)
print(l1)

[ 30  27  24  21  18  15  12   9   6   3   0  -3  -6  -9 -12 -15 -18 -21
 -24 -27]


In [ ]:
# Mathematical
a = np.array([1,2,3])
b = np.array([3,4,6])

print(f'The sum of a and b is {a+b}')
print(f'The diff of a and b is {a-b}')
print(f'The product of a and b is {a*b} ')
print(f'The division of a and b is {a/b}')

The sum of a and b is [4 6 9]
The diff of a and b is [-2 -2 -3]
The product of a and b is [ 3  8 18] 
The division of a and b is [0.33333333 0.5        0.5       ]


In [ ]:
# matrix multiplication
b1 = np.array([[1,2,3],[2,3,4]])
b2 = np.array([[6,7],[8,9],[6,3]])

# Dot product --- product = AB -- A m x n -- B m x n
c = np.dot(b1,b2)
print(b1)

[[1 2 3]
 [2 3 4]]


In [ ]:
print(b2)

[[6 7]
 [8 9]
 [6 3]]


In [ ]:
[

]